# Aquisição e Leitura de Dados Reais

> Dados das aulas disponíveis no [repositório do curso](https://github.com/alura-tech/pos-datascience-analise-e-exploracao-de-dados/archive/refs/heads/Dados.zip) no GitHub

* Referências
  * [DataSUS](https://datasus.saude.gov.br/)
  * [Documentação Pandas](https://pandas.pydata.org/)

In [1]:
from urllib.request import urlretrieve
from pathlib import Path
from zipfile import ZipFile

DATA_URL = 'https://github.com/alura-tech/pos-datascience-analise-e-exploracao-de-dados/archive/refs/heads/Dados.zip'
DATA_PATH_RAW = './data/raw'
DATA_PATH_EXTRACTED = './data/interim'

Path(DATA_PATH_RAW).mkdir(parents=True, exist_ok=True)
Path(DATA_PATH_EXTRACTED).mkdir(parents=True, exist_ok=True)

urlretrieve(DATA_URL, DATA_PATH_RAW + '/data.zip')

with ZipFile(DATA_PATH_RAW + '/data.zip') as zip_ref:
    zip_ref.extractall(DATA_PATH_EXTRACTED)

In [2]:
import pandas as pd

In [3]:
! head -n 5 ./data/interim/pos-datascience-analise-e-exploracao-de-dados-Dados/A150850189_28_143_208.csv

 Procedimentos hospitalares do SUS - por local de interna��o - Brasil
Valor total por Unidade da Federa��o e Ano/m�s atendimento
Per�odo:Jan/2008-Set/2021
"Unidade da Federa��o";"1992/Mar";"1992/Abr";"1993/Mai";"1993/Dez";"1994/Jan";"1994/Fev";"1994/Mai";"1994/Ago";"1994/Nov";"1995/Jan";"1995/Mar";"1995/Jun";"1995/Ago";"1995/Dez";"1996/Fev";"1996/Mar";"1996/Ago";"1996/Dez";"1997/Fev";"1997/Nov";"1998/Fev";"1998/Mar";"1998/Jul";"1998/Ago";"1998/Set";"1998/Out";"1998/Dez";"1999/Fev";"1999/Mar";"1999/Mai";"1999/Jul";"1999/Ago";"1999/Set";"1999/Out";"1999/Nov";"1999/Dez";"2000/Jan";"2000/Fev";"2000/Mar";"2000/Abr";"2000/Mai";"2000/Jun";"2000/Jul";"2000/Ago";"2000/Set";"2000/Out";"2000/Nov";"2000/Dez";"2001/Jan";"2001/Fev";"2001/Mar";"2001/Abr";"2001/Mai";"2001/Jun";"2001/Jul";"2001/Ago";"2001/Set";"2001/Nov";"2001/Dez";"2002/Jan";"2002/Fev";"2002/Mar";"2002/Mai";"2002/Jun";"2002/Jul";"2002/Out";"2002/Nov";"2002/Dez";"2003/Jan";"2003/Fev";"2003/Mar";"2003/Abr";"2003/Jun";"2003/Jul";"2003/Ago";"2003/Out";"2003/Nov";"2003/Dez";"2004/Jan";"2004/Fev";"2004/Mar";"2004/Abr";"2004/Mai";"2004/Jun";"2004/Jul";"2004/Ago";"2004/Set";"2004/Out";"2004/Nov";"2004/Dez";"2005/Jan";"2005/Fev";"2005/Mar";"2005/Abr";"2005/Mai";"2005/Jun";"2005/Jul";"2005/Ago";"2005/Set";"2005/Out";"2005/Nov";"2005/Dez";"2006/Jan";"2006/Fev";"2006/Mar";"2006/Abr";"2006/Mai";"2006/Jun";"2006/Jul";"2006/Ago";"2006/Set";"2006/Out";"2006/Nov";"2006/Dez";"2007/Jan";"2007/Fev";"2007/Mar";"2007/Abr";"2007/Mai";"2007/Jun";"2007/Jul";"2007/Ago";"2007/Set";"2007/Out";"2007/Nov";"2007/Dez";"2008/Jan";"2008/Fev";"2008/Mar";"2008/Abr";"2008/Mai";"2008/Jun";"2008/Jul";"2008/Ago";"2008/Set";"2008/Out";"2008/Nov";"2008/Dez";"2009/Jan";"2009/Fev";"2009/Mar";"2009/Abr";"2009/Mai";"2009/Jun";"2009/Jul";"2009/Ago";"2009/Set";"2009/Out";"2009/Nov";"2009/Dez";"2010/Jan";"2010/Fev";"2010/Mar";"2010/Abr";"2010/Mai";"2010/Jun";"2010/Jul";"2010/Ago";"2010/Set";"2010/Out";"2010/Nov";"2010/Dez";"2011/Jan";"2011/Fev";"2011/Mar";"2011/Abr";"2011/Mai";"2011/Jun";"2011/Jul";"2011/Ago";"2011/Set";"2011/Out";"2011/Nov";"2011/Dez";"2012/Jan";"2012/Fev";"2012/Mar";"2012/Abr";"2012/Mai";"2012/Jun";"2012/Jul";"2012/Ago";"2012/Set";"2012/Out";"2012/Nov";"2012/Dez";"2013/Jan";"2013/Fev";"2013/Mar";"2013/Abr";"2013/Mai";"2013/Jun";"2013/Jul";"2013/Ago";"2013/Set";"2013/Out";"2013/Nov";"2013/Dez";"2014/Jan";"2014/Fev";"2014/Mar";"2014/Abr";"2014/Mai";"2014/Jun";"2014/Jul";"2014/Ago";"2014/Set";"2014/Out";"2014/Nov";"2014/Dez";"2015/Jan";"2015/Fev";"2015/Mar";"2015/Abr";"2015/Mai";"2015/Jun";"2015/Jul";"2015/Ago";"2015/Set";"2015/Out";"2015/Nov";"2015/Dez";"2016/Jan";"2016/Fev";"2016/Mar";"2016/Abr";"2016/Mai";"2016/Jun";"2016/Jul";"2016/Ago";"2016/Set";"2016/Out";"2016/Nov";"2016/Dez";"2017/Jan";"2017/Fev";"2017/Mar";"2017/Abr";"2017/Mai";"2017/Jun";"2017/Jul";"2017/Ago";"2017/Set";"2017/Out";"2017/Nov";"2017/Dez";"2018/Jan";"2018/Fev";"2018/Mar";"2018/Abr";"2018/Mai";"2018/Jun";"2018/Jul";"2018/Ago";"2018/Set";"2018/Out";"2018/Nov";"2018/Dez";"2019/Jan";"2019/Fev";"2019/Mar";"2019/Abr";"2019/Mai";"2019/Jun";"2019/Jul";"2019/Ago";"2019/Set";"2019/Out";"2019/Nov";"2019/Dez";"2020/Jan";"2020/Fev";"2020/Mar";"2020/Abr";"2020/Mai";"2020/Jun";"2020/Jul";"2020/Ago";"2020/Set";"2020/Out";"2020/Nov";"2020/Dez";"2021/Jan";"2021/Fev";"2021/Mar";"2021/Abr";"2021/Mai";"2021/Jun";"2021/Jul";"2021/Ago";"2021/Set";"Total"
"11 Rond�nia";-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;604,33;-;-;-;-;-;4209,37;16397,03;133645,19;346912,84;711758,31;1829559,71;1940792,63;1955721,68;2143353,81;2280382,58;2624542,97;2973421,02;2938286,29;2843930,91;2878153,20;2780022,62;2651804,89;3147566,24;3082108,12;4190355,33;4040251,62;3946423,71;3372377,96;3720608,86;3787323,26;3679369,94;3866146,99;3667808,60;3633471,79;3812315,59;3911776,03;4663060,75;4524544,88;4778755,26;4369733,23;4632439,12;4464307,47;4668642,02;4490368,23;4423840,08;4384430,09;4173529,95;4293085,61;4674947,02;5087527,81;4724192,54;4690112,05;4319488,17;4778472,22;4202805,84;4372265,77;4389025,81;4045339,34;4472721,53;4417486,20;4859795,35;4590008,82;4579463,54;4467858,99;4160296,03;4315005,38;4043314,46;4289759,65;4138600,85;3966744,30;4471693,32;4378412,90;5495946,92;5380890,26;5170015,34;4899586,21;5526959,19;5889685,39;6367552,03;6299844,72;6685861,76;6163036,06;6349302,00;6059111,35;6740436,14;6584249,21;7558087,91;6934864,98;7150611,14;6957882,67;7057715,90;7096778,40;6965306,56;6803544,72;6983698,79;6624059,46;7501596,28;7365022,91;7645734,88;7545619,91;7438604,96;7233618,24;7425981,15;7654315,58;7429006,24;7580768,75;7025175,60;6760305,81;7779822,21;7707892,66;8560529,90;8355165,66;7845709,98;7931146,33;7554941,74;7963674,01;6964512,59;7174445,57;7007236,18;7154710,19;8762491,60;8133488,55;8140639,49;8041248,80;8199032,67;8363386,07;7889819,50;8603943,85;8048398,25;8159737,49;8457455,71;7766983,20;8858845,57;8407076,44;9492938,92;8206195,92;9011612,58;9124967,84;8406732,72;8411360,02;8651081,66;8193425,99;8388269,45;8645315,78;9050329,13;9211262,51;9490545,02;8600886,20;8919190,86;8909111,89;8409386,09;8924348,41;8948605,66;8660753,05;8328381,43;8431334,62;7251287,20;7491953,39;8962121,79;11069824,97;10608659,34;11578639,50;9017298,72;8280299,95;8909539,74;9469279,43;10045624,39;10677245,18;18147121,02;17753851,45;17659855,79;14435903,47;11834435,10;7371334,84;1682801,60;1088059702,25

In [4]:
FILE_PATH = './data/interim/pos-datascience-analise-e-exploracao-de-dados-Dados/A150850189_28_143_208.csv'

df = pd.read_csv(FILE_PATH,
                 encoding='ISO-8859-1', # Latin One
                 skiprows=3,
                 sep=';',
                 skipfooter=12,
                 thousands='.',
                 decimal=',')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Columns: 293 entries, Unidade da Federação to Total
dtypes: float64(170), object(123)
memory usage: 61.9+ KB

/tmp/ipykernel_22696/1278751246.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(FILE_PATH,

In [5]:
df.head()

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
0,11 Rondônia,-,-,-,-,-,-,-,-,-,...,10045624.39,10677245.18,18147121.02,17753851.45,17659855.79,14435903.47,11834435.10,7371334.84,1682801.60,1.088060e+09
1,12 Acre,-,-,-,-,-,-,-,-,-,...,4175526.06,5282655.42,5699597.78,5002272.59,4326882.24,3458187.11,2302711.01,1196754.85,-,4.752903e+08
2,13 Amazonas,-,-,-,-,-,-,-,-,-,...,27406458.57,22341042.63,27923786.94,24515920.09,23973537.71,22175398.40,21614943.55,13806958.66,5292323.36,2.061943e+09
3,14 Roraima,-,-,-,-,-,-,-,-,-,...,3557821.99,4172285.82,5427226.70,4192540.54,3681417.80,3475205.55,3320807.96,2907871.07,1496814.75,3.525463e+08
4,15 Pará,-,-,-,-,-,-,-,-,-,...,39042349.46,37113440.70,49625416.13,52558327.29,50907226.77,43876590.47,33718084.12,20837865.89,4620263.03,4.968812e+09

In [6]:
df.tail()

,Unidade da Federação,1992/Mar,1992/Abr,1993/Mai,1993/Dez,1994/Jan,1994/Fev,1994/Mai,1994/Ago,1994/Nov,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
22,43 Rio Grande do Sul,-,-,-,-,-,-,-,-,-,...,1.159919e+08,1.267303e+08,1.696877e+08,1.453025e+08,1.550843e+08,1.428123e+08,1.128054e+08,74954589.62,25200345.68,1.361334e+10
23,50 Mato Grosso do Sul,-,-,-,-,-,-,-,-,-,...,2.472700e+07,2.560076e+07,3.250618e+07,3.310106e+07,3.688563e+07,3.159520e+07,2.071197e+07,11302985.98,2445267.12,2.516383e+09
24,51 Mato Grosso,-,-,-,-,-,-,-,-,-,...,1.888971e+07,2.154459e+07,3.579084e+07,3.753402e+07,3.785947e+07,3.493713e+07,2.936420e+07,19849249.43,7325067.61,2.386584e+09
25,52 Goiás,-,-,-,-,-,-,-,-,-,...,4.263870e+07,4.571547e+07,7.446406e+07,6.863041e+07,6.946733e+07,6.716235e+07,5.789129e+07,44939821.34,18860370.17,5.380179e+09
26,53 Distrito Federal,-,-,-,-,-,-,-,-,-,...,2.448472e+07,2.415606e+07,3.639103e+07,3.564176e+07,3.243456e+07,2.719646e+07,2.626552e+07,22156437.60,13173812.37,2.778457e+09

In [7]:
pd.options.display.float_format = '{:.2f}'.format

In [8]:
df.describe()

,2007/Ago,2007/Set,2007/Out,2007/Nov,2007/Dez,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,...,2020/Dez,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,Total
count,27.00,27.00,27.00,27.00,27.00,27.00,27.00,27.00,27.00,27.00,...,27.00,27.00,27.00,27.00,27.00,27.00,27.00,27.00,27.00,27.00
mean,304952.77,788145.26,2440162.96,5517354.05,12337159.42,76872923.93,23825025.66,25882844.71,26215278.28,26221049.45,...,57043175.42,58917158.65,59070927.95,81749309.03,81142931.26,87271862.20,77590406.47,60846287.01,43885716.30,6852320913.49
std,392806.00,1071747.56,3421972.10,7767711.29,16345863.65,203345357.97,34476004.08,34826830.50,34796463.86,35071861.23,...,71812939.93,75886774.58,74250282.54,104151498.28,103731994.30,113210161.00,103596516.21,82898209.94,62018534.41,9169866693.74
min,4113.76,11858.63,43852.67,226661.18,470676.43,808448.39,771687.83,876091.18,896952.53,1027288.73,...,2841469.69,2786277.13,2664375.13,3960131.30,4192540.54,3681417.80,3458187.11,2302711.01,1196754.85,337181964.14
25%,46580.42,139423.94,505778.42,1410610.81,3650090.00,8257222.37,7932273.51,8926011.35,8764559.62,9229049.70,...,19073133.75,19522001.10,20977269.17,29399477.97,26964958.13,27262112.33,24095597.98,18724376.30,11348430.84,2224263694.82
50%,179395.82,418053.58,1152115.25,2406035.32,5949408.99,16599004.84,10215956.80,12262049.08,12453466.98,11900817.00,...,29093489.77,27452425.03,28344652.94,37147348.21,38411419.09,41819897.10,34937134.14,29364200.76,20837865.89,2867428082.03
75%,392985.52,969999.75,2625635.63,5915821.61,13394973.35,52156843.27,26932691.98,30400866.02,30982776.89,31307258.67,...,79372320.79,79191784.05,81887992.15,100967867.00,108236362.28,117460819.75,106300830.46,79844137.72,55265343.61,8818298482.19
max,1665349.90,4434168.64,14577395.84,35032259.98,76668547.41,1049827695.26,173062308.33,170621304.31,170389849.75,172513744.39,...,338634303.39,361427087.80,352846447.86,502905607.53,504427182.45,548112705.83,503160959.54,404373175.61,301986341.98,44290790025.14